name: Carnival CI

on:
  push:
    branches: 
      - main
      - refactor
    paths-ignore:
      - "docs/**"
      
  pull_request:
    branches: 
      - main
      - refactor
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main

      - name: Install 🔧
        run: npm install

      - name: Test 🚨
        run: npm test

      - name: Build 🏗️
        run: npm run build
